spring:
  mvc:
    pathmatch:
      # 解决 SpringBoot2.6.x 整合 knife4j 启动报错。
      # SpringBoot2.6.x以及上版本默认使用的 PATH_PATTERN_PARSER 而 knife4j 的 springfox 使用的是 ANT_PATH_MATCHER 导致的，SpringBoot 的 yml 文件配置 url 匹配规则
      matching-strategy: ANT_PATH_MATCHER
  profiles:
    active: @profile.name@

shiro:
  loginUrl: /sys/common/login
  unauthorizedUrl: /sys/common/403

reid:
  # swagger 配置
  swagger:
    # 需要扫描的包路径
    basePackage: org.reid.smart
    companyName: 一个无聊的公司
    name: 一个无聊的项目
    version: @project.version@
    description: 一个无聊的项目后台API接口
  # shiro 配置
  shiro:
    # 是否启用 shiro
    enableShiro: true
    # 不需要拦截的地址
    excludeUrls: /sys/common/login,/sys/common/test
  # mybatis、mybatis-plus 配置
  mybatis:
    mapperScanner:
      # 需要扫描 mapper 的位置
      basePackage: org.reid.smart.modules.**.mapper*
