spring:
  mvc:
    pathmatch:
      # 解决 SpringBoot2.6.x 整合 knife4j 启动报错。
      # SpringBoot2.6.x以及上版本默认使用的 PATH_PATTERN_PARSER 而 knife4j 的 springfox 使用的是 ANT_PATH_MATCHER 导致的，SpringBoot 的 yml 文件配置 url 匹配规则
      matching-strategy: ANT_PATH_MATCHER
  profiles:
    active: @profile.name@

reid:
  swagger:
    base-package: org.reid.smart
    companyName: 一个无聊的公司
    name: 一个无聊的项目
    version: @project.version@
    description: 一个无聊的项目后台API接口

