spring:
  mvc:
    pathmatch:
      # 解决 SpringBoot2.6.x 整合 knife4j 启动报错。
      # SpringBoot2.6.x以及上版本默认使用的 PATH_PATTERN_PARSER 而 knife4j 的 springfox 使用的是 ANT_PATH_MATCHER 导致的，SpringBoot 的 yml 文件配置 url 匹配规则
      matching-strategy: ANT_PATH_MATCHER
  profiles:
    active: @profile.name@

shiro:
  loginUrl: /sys/common/login
  unauthorizedUrl: /sys/common/403

reid:
  # swagger 配置
  swagger:
    # 需要扫描的包路径（默认扫描 com 下全部）
    basePackage: org.reid.smart
    # 以下非必须配置
    companyName: 一个无聊的公司
    applicationName: 一个无聊的项目
    applicationVersion: @project.version@
    applicationDescription: 一个无聊的项目后台API接口
  # shiro 配置
  shiro:
    # 是否启用 shiro
    enableShiro: false
    # 不需要拦截的地址（内置有一些插件静态方法不做拦截，如：swagger）
    excludeUrls: /sys/common/login,/sys/common/test
    # 登录地址
    loginUrl: /sys/common/login
    # 未授权地址
    unauthorizedUrl: /sys/common/403
  # mybatis、mybatis-plus 配置
  mybatis:
    # 需要扫描 mapper 的位置（必须）
    mapperScan: org.reid.smart.modules.**.mapper*
