spring:
  mvc:
    pathmatch:
      # 解决 SpringBoot2.6.x 整合 knife4j 启动报错。
      # SpringBoot2.6.x以及上版本默认使用的 PATH_PATTERN_PARSER 而 knife4j 的 springfox 使用的是 ANT_PATH_MATCHER 导致的，SpringBoot 的 yml 文件配置 url 匹配规则
      matching-strategy: ANT_PATH_MATCHER
  profiles:
    active: @profile.name@

shiro:
  loginUrl: /sys/common/login
  unauthorizedUrl: /sys/common/403

reid:
  # swagger 配置
  swagger:
    # 需要扫描的包路径（默认扫描 com 下全部）
    base-package: org.reid.smart
    # 以下非必须配置
    author-name: 一个无聊的程序猿
    contact-url: company-url
    contact-email: 1184010001@qq.com
    application-name: 一个无聊的项目
    application-version: @project.version@
    application-description: 一个无聊的项目后台API接口
  # shiro 配置
  shiro:
    # 是否启用 shiro
    enable-shiro: false
    # 不需要拦截的地址（内置有一些插件静态方法不做拦截，如：swagger）
    exclude-urls: /sys/login,/sys/common/test
    # 登录地址
    login-url: /sys/common/login
    # 未授权地址
    unauthorized-url: /sys/common/403
    # 会话踢出后到的地址
    kickout-url: /auth/kickout
  # mybatis、mybatis-plus 配置
  mybatis:
    # 需要扫描 mapper 的位置（必须）
    mapper-scan: org.reid.smart.modules.**.mapper*
  mqtt:
    host: ws://81.68.151.90:8083/mqtt # ws://broker-cn.emqx.io:8083/mqtt,ws://broker.emqx.io:8083/mqtt
