server:
  port: 9999
  servlet:
    context-path: /reid-smart-pro

# swagger
knife4j:
  # 开启增强配置
  enable: true
  # 开启生产环境屏蔽
  production: true
  basic:
    enable: true
    username: reid
    password: reid1314
